import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
  Home,
  Clock,
  BookOpen,
  Link,
  Archive,
  Sparkles,
  type Icon as LucideIcon,
} from "lucide-react";
import { GitHub, SiteLogo } from "@/assets/icons";

export type Icon = LucideIcon;

export const Icons = {
  book: BookOpen,
  logo: SiteLogo,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  gitHub: GitHub,
  twitter: Twitter,
  check: Check,
  home: Home,
  clock: Clock,
  link: Link,
  archive: Archive,
  sparkles: Sparkles,
};
